import Head from "next/head";
import Image from "next/image";
import MainPage from "../components/MainPage";
import SearchBar from "../components/SearchBar";
import SideNavBar from "../components/SideNavBar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <SideNavBar />
        <div className="w-full">
          <SearchBar />
          <MainPage />
        </div>
      </div>
    </div>
  );
}
